config/routes.rb
Dream::Application.routes.draw do

  resources :products

  get 'static_pages/faq'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/privacy'

  resources :posts

  resources :categories


  match '/contacts', to: 'contacts#new', via: 'get'
  resources 'contacts', only: [:new, :create]


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users


end

app/models/category.rb
class Category < ActiveRecord::Base
 attr_accessible :name
  validates_presence_of :name
  has_and_belongs_to_many :posts

end

app/controllers/categories_controller.rb
class CategoriesController < InheritedResources::Base
  class CategoriesController < ApplicationController
    before_filter :authenticate_user!, :except => [:index]
    # before_filter :authenticate_user!, :except => [:show,:index]
    load_and_authorize_resource


    # GET /categories
    # GET /categories.json

    def index
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json:@categories }
      end
    end

    # GET /categories/1
    # GET /categories/1.json
    def show
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json:@category }
      end
    end

    # GET /categories/new
    # GET /categories/new.json
    def new
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json:@category }
      end
    end

    # GET /categories/1/edit
    def edit

    end

    # POST /categories
    # POST /categories.json
    def create
      respond_to do |format|
        if @category.save
          format.html { redirect_to @category, notice:'Category was successfully created.' }
          format.json { render json:@category, status => :created, location => @category }
        else
          format.html { render action => "new" }
          format.json { render json:@category.errors, status => :unprocessable_entity }
        end
      end
    end

    # PUT /categories/1
    # PUT /categories/1.json
    def update
      respond_to do |format|
        if @category.update_attributes(params[:category])
          format.html { redirect_to @category, notice => 'Category was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action => "edit" }
          format.json { render json => @category.errors, status => :unprocessable_entity }
        end
      end
    end

    # DELETE /categories/1
    # DELETE /categories/1.json
    def destroy
      @category.destroy
      respond_to do |format|
        format.html { redirect_to categories_url }
        format.json { head :no_content }
      end
    end
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<div class="authform">
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => 'button radius' %>
  </div>
        </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category, :class => 'button radius' %> |
<%= link_to 'Back', categories_path, :class => 'button radius' %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category, :class => 'button radius' %></td>
        <td><%= link_to 'Edit', edit_category_path(category), :class => 'button radius' %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?', :class => 'button radius' }, :class => 'button radius' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path, :class => 'button radius' %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path , :class => 'button radius' %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) , :class => 'button radius' %>
<%= link_to 'Back', categories_path, :class => 'button radius' %>