config/routes.rb
Dream::Application.routes.draw do

  resources :products

  get 'static_pages/faq'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/privacy'

  resources :posts

  resources :categories


  match '/contacts', to: 'contacts#new', via: 'get'
  resources 'contacts', only: [:new, :create]


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users


end

app/models/product.rb
class Product < ActiveRecord::Base

  attr_accessible  :nazov, :farba, :velkost, :mnozstvo

end

def self.to_csv(options = {})
  CSV.generate(options) do |csv|
    csv << column_names
    all.each do |product|
      csv << product.attributes.values_at(*column_names)
    end
  end

  def self.xml_parser
    xml_string = open("#{Rails.root}/abc.xml").read
    root = Nokogiri::XML(xml_string)
    products = root.xpath("products/product")
    products.each do |product|
      product_hash = {
          nazov:  product.at_xpath("name").text,
          farba: product.at_xpath("farba").text,
          velkost: product.at_xpath("velkost").text,
          mnozstvo: product.at_xpath("mnozstvo").text,
      }
      product_record = Product.create!(product_hash)
      product_record.save

    end
  end
end

app/controllers/products_controller.rb
class ProductsController < InheritedResources::Base
  def index
    @products = Product.order(:nazov)
    respond_to do |format|
      format.html
      format.csv { send_data @products.to_csv }
      format.xls # { send_data @products.to_csv(col_sep: "\t") }
    end
  end
  end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class="authform">

<%= simple_form_for(@product) do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
    <%= f.input :nazov %>
    <%= f.input :mnozstvo %>
    <%= f.input :farba, :as => :select,
                :label => "Farba", :include_blank => false,
                :collection => [["Biela", 1], ["Červená", 2], ["Zelená", 3]] %>
    <%= f.input :velkost, :as => :select,
                :label => "Veľkosť", :include_blank => false,
                :collection => [["6", 1], ["6 1/5", 2], ["7", 3], ["7 1/5", 4]] %>
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>
</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="row fullblue">
  <div class="medium-8 medium-centered columns centered-text">
  <p>
    Download:
    <%= link_to "CSV", products_path(format: "csv") %> |
    <%= link_to "Excel", products_path(format: "xls") %>
  </p>
</div>

  </div>
  <div class="row fullblue">
    <div class="medium-8 medium-centered columns centered-text">
<h1>Zoznam produktov</h1>

<table>
  <thead>
    <tr>
      <th>Nazov</th>
      <th>Farba</th>
      <th>Velkost</th>
      <th>Mnozstvo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>

        <td><%= product.nazov %></td>
        <td><%= product.farba %></td>
        <td><%= product.velkost %></td>
        <td><%= product.mnozstvo %></td>
        <td><%= link_to 'Zobraz', product %></td>
        <td><%= link_to 'Edituj', edit_product_path(product) %></td>
        <td><%= link_to 'Vymaž', product, method: :delete, data: { confirm: 'Si si istý?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Vlož nový tovar', new_product_path %>

</div>
    </div>
    </div>

app/views/products/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:o="urn:schemas-microsoft-com:office:office"
          xmlns:x="urn:schemas-microsoft-com:office:excel"
          xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Produkt_kod</Data></Cell>
        <Cell><Data ss:Type="String">Nazov</Data></Cell>
        <Cell><Data ss:Type="String">Farba</Data></Cell>
        <Cell><Data ss:Type="String">Velkost</Data></Cell>
        <Cell><Data ss:Type="String">Mnozstvo</Data></Cell>
      </Row>
      <% @products.each do |product| %>
          <Row>
            <Cell><Data ss:Type="Number"><%= product.id %></Data></Cell>
            <Cell><Data ss:Type="Number"><%= product.produkt_kod %></Data></Cell>
            <Cell><Data ss:Type="String"><%= product.nazov %></Data></Cell>
            <Cell><Data ss:Type="String"><%= product.farba %></Data></Cell>
            <Cell><Data ss:Type="Number"><%= product.velkost %></Data></Cell>
            <Cell><Data ss:Type="Number"><%= product.mnozstvo %></Data></Cell>
          </Row>
      <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/products/new.html.erb
<div class="row fullblue">
  <div class="medium-8 medium-centered columns centered-text">
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>
</div>
    </div>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Nazov:</strong>
  <%= @product.nazov %>
</p>

<p>
  <strong>Farba:</strong>
  <%= @product.farba %>
</p>

<p>
  <strong>Velkost:</strong>
  <%= @product.velkost %>
</p>

<p>
  <strong>Mnozstvo:</strong>
  <%= @product.mnozstvo %>
</p>
<p id="pdf_link"><%= link_to "Download Invoice (PDF)", product_path(@product, :format => "pdf") %></p>
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>