config/routes.rb
Dream::Application.routes.draw do

  resources :products

  get 'static_pages/faq'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/privacy'

  resources :posts

  resources :categories


  match '/contacts', to: 'contacts#new', via: 'get'
  resources 'contacts', only: [:new, :create]


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users


end

app/views/layouts/_footer.html.erb
<section>
<div class="row">
  <div class="12-large-columns">

    <div class="large-5 columns">
<<<<<<< Updated upstream
          <!--<p><img src="/assets/images/renomaniawhite.png" /></p>-->
=======
      <a href="../"><img src =  "../assets/convwhite.png" ></a>
>>>>>>> Stashed changes
          <p>&copy; peterkona.com | <a href="#">Privacy Policy</a></p>
        </div>

        <!--<div class="small-2 columns">-->
          <!--<p><%= link_to 'About us', static_pages_about_path%></p>-->
          <!--<p><%= link_to 'Contact us', static_pages_contact_path%></p>-->
          <!--<p><%= link_to 'Privacy', static_pages_privacy_path%></p>-->
          <!--<p><%= link_to 'Faq', static_pages_faq_path%></p>-->
        <!--</div>-->
    <!---->
        <!--<div class="large-2 columns">-->
          <!--<p><a href="http://twitter.com"><img src="/assets/images/webicon-twitter-m.png" align="absmiddle" /> Twitter</a></p>-->
          <!--<p><a href="http://facebook.com"><img src="/assets/images/webicon-facebook-m.png" align="absmiddle" /> Facebook</a></p>-->
          <!--<p><a href="#"><img src="/assets/images/webicon-mail-m.png" align="absmiddle" /> Email Us</a></p>-->
        <!--</div>-->
    <!---->
        <!--<div class="large-3 columns">-->
          <!--<p>Newsletter:</p>-->
          <!--<p><input type="text" value="Email Address"><input type="submit" class="tiny button radius right"></p>-->
        <!--</div>-->

   </div>
</div>

</section>
  <!--<script src="stickyFooter.js"></script>-->

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>


<nav class="top-bar" data-topbar class="fixed">
  <ul class="title-area">
    <!--<li class="name">-->
<<<<<<< Updated upstream
    <li class="name"><a href='../'>PETER KONA</a><li class="divider"></li>
=======
    <li class="name"><a href="../"><img src =  "../assets/logo.png" ></a><li class="divider"></li>
>>>>>>> Stashed changes
</li>
  </ul>


    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  <div class="top-bar-section">
    <ul>

      <!--<li class="name"%= link_to current_user.email,"#" %></li>-->

      <!--links to static pages about_us,contact privacy and Faq, with path-->
<<<<<<< Updated upstream

      <li class="name"><%= link_to 'About me', static_pages_about_path%></li>
      <li class="divider"></li>
      <!--<li class="name"><%= link_to 'Gallery', static_pages_privacy_path%></li>-->
      <li class="divider"></li>

      <li class="name"><%= link_to 'Contact me', contacts_path%></li>
=======
>>>>>>> Stashed changes
      <li class="divider"></li>
      <!--rendering layout from layouts/navigation_links it renders links based on role-->
      <ul class = "right"></ul>
      <li><%= link_to 'Produkty', products_path %></li>
      <%= render 'layouts/navigation_links' %>


    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<!--logical dividing of links based on roles-->
<div class="top-bar-section">
  <ul>

<% if user_signed_in? %>

  <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
        <li class="divider"></li>
  <li ><%= link_to 'Login', new_user_session_path %></li>
        <li class="divider"></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Zmeň konto', edit_user_registration_path %></li>
<% else %>
        <li class="divider"></li>

  <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <li class="divider"></li>
    <% end %>

<!--if you sign in as bussines -->

<% if user_signed_in? %>
    <% if current_user.is_vendor? %>
  <li><%= link_to 'Vitajte', static_pages_contact_path %></li>
<% end %>
   <% end %>ä
    <li class="divider"></li>
<!--if you sign in as bussines -->

<% if user_signed_in? %>
    <% if current_user.is_vendor? %>
    <li><%= link_to 'Produkty', products_path %></li>

        <% end %>
    <% end %>

<!--if you sign in as bussines -->

<!--<% if user_signed_in? %>-->
    <!--<% if current_user.is_vendor? %>-->
<<<<<<< Updated upstream
    <!--<li><%= link_to 'Categories', categories_path %></li>-->
=======
    <!--<li><%= link_to 'Produkty', products_path %></li>-->
>>>>>>> Stashed changes

    <!--<% end %>-->
<!--<% end %>-->

<!--if you sign in as customer -->


<% if user_signed_in? %>
    <% if current_user.is_customer? %>
        <li><%= link_to 'Produkty', products_path %></li>

    <% end %>
<% end %>

</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Dream" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Dream" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header class="fixed shadow">
<!--render top navigation bar-->
     <!--<nav class="top-bar">-->

      <%= render 'layouts/navigation' %>

     <!--</nav>-->
<!--render layout message if login is successfull or not -->
    </header>

   <article class="content">

       <%= render 'layouts/messages' %>
       <%= yield %>
   </article>
<!--render footer layout-->


    <footer class="shadow">
      <%= render 'layouts/footer' %>

    </footer>



    <!-- Included JS Files (Compressed) -->
    <script src="jquery.js"></script>
    <script src="foundation.min.js"></script>
    <script src="stickyFooter.js"></script>
    <script src="javascripts/jquery.foundation.orbit.js"></script>
    <!-- Initialize JS Plugins -->
    <script src="app.js"></script>
  </body>

</html>